module.exports = {
	content: ['./src/**/*.{js,jsx,ts,tsx}', './public/index.html'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				primary: '#565e74',
				'on-secondary': '#f8f8ff',
				'inverse-primary': '#dae2fd',
				'primary-fixed-dim': '#ccd4ee',
				'secondary-container': '#d5e3fc',
				'surface-bright': '#f7f9fb',
				error: '#9f403d',
				'tertiary-container': '#dcddfe',
				'inverse-surface': '#0b0f10',
				'error-container': '#fe8983',
				'surface-container': '#e8eff3',
				'tertiary-fixed-dim': '#cecfef',
				'on-tertiary-container': '#4c4e69',
				'on-secondary-fixed': '#324053',
				'on-surface-variant': '#566166',
				'error-dim': '#4e0309',
				'on-background': '#2a3439',
				'on-primary-fixed': '#373f54',
				'surface-dim': '#cfdce3',
				'primary-dim': '#4a5268',
				'on-error': '#fff7f6',
				'inverse-on-surface': '#9a9d9f',
				'secondary-fixed': '#d5e3fc',
				'on-error-container': '#752121',
				'on-surface': '#2a3439',
				secondary: '#526074',
				'on-secondary-container': '#455367',
				tertiary: '#5b5d78',
				'on-primary-container': '#4a5167',
				'surface-tint': '#565e74',
				'surface-container-highest': '#d9e4ea',
				'primary-container': '#dae2fd',
				'on-primary-fixed-variant': '#535b71',
				'surface-container-high': '#e1e9ee',
				'tertiary-fixed': '#dcddfe',
				'surface-container-low': '#f0f4f7',
				'secondary-dim': '#465468',
				'surface-container-lowest': '#ffffff',
				'tertiary-dim': '#4f516c',
				background: '#f7f9fb',
				'secondary-fixed-dim': '#c7d5ed',
				'on-secondary-fixed-variant': '#4e5c71',
				'surface-variant': '#d9e4ea',
				'on-tertiary-fixed': '#393c55',
				'on-primary': '#f7f7ff',
				'primary-fixed': '#dae2fd',
				'on-tertiary-fixed-variant': '#565873',
				outline: '#717c82',
				surface: '#f7f9fb',
				'on-tertiary': '#fbf8ff',
				'outline-variant': '#a9b4b9',
			},
			borderRadius: {
				DEFAULT: '0.125rem',
				lg: '0.25rem',
				xl: '0.5rem',
				full: '0.75rem',
			},
			fontFamily: {
				headline: ['Manrope', 'sans-serif'],
				body: ['Manrope', 'sans-serif'],
				label: ['Manrope', 'sans-serif'],
			},
		},
	},
	plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
